# Generated by Django 5.2 on 2025-04-22 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='书籍分类')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'db_table': 'lms_book_category',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='书籍名称')),
                ('author', models.CharField(max_length=200, null=True, verbose_name='作者')),
                ('publisher', models.CharField(max_length=200, null=True, verbose_name='出版社')),
                ('pub_date', models.DateField(auto_now_add=True, null=True, verbose_name='出版日期')),
                ('qty', models.IntegerField(default=0, verbose_name='库存数量')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('book_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lms.bookcategory', verbose_name='书籍分类')),
            ],
            options={
                'db_table': 'lms_book',
            },
        ),
    ]
